# Generated by Django 5.0.4 on 2024-06-26 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_activate',
            new_name='is_active',
        ),
    ]
